
server:
  port: 7080
 
spring:
  application:
    name: DEV ENVIRONMENT
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/junitdb?createDatabaseIfNotExist=true
    username: ${Database}
    password: ${Password}
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
mvc:
  pathmatch:
    matching-strategy: ANT_PATH_MATCHER